
@host=ec2-54-91-8-233.compute-1.amazonaws.com:3000 

# @name login
POST http://{{host}}/auth/login HTTP/1.1
content-type: application/x-www-form-urlencoded

email={{$processEnv TAG_AUTH_LOGIN}}&password={{$processEnv TAG_AUTH_PASSWORD}}

@authToken = {{login.response.body.access_token}}
###

# @name listar_alimentos
GET http://{{host}}/foods HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name listar_cardapios
GET http://{{host}}/food/menu HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name listar_estoque
GET http://{{host}}/food/inventory HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name students
GET http://{{host}}/students HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 


# @name create_student
POST  http://{{host}}/students HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Aluno teste com mais caracteres",
    "register_type": "RG",
    "sex": 0,
    "color_race": 0,
    "filiation": 0,
    "nationality": 0,
    "birthday": "2013-02-04",
    "send_year": 2020,
    # "school_inep_id_fk": "123456789",
    "edcenso_uf_fk": "61a92b6dd2b8a11704d7ae6a",
    "edcenso_city_fk": "61a92c8ed2b8a11704d813fe",
    "edcenso_district_fk": "61a93a0781524118745b6314"
}

### 

# @name school
GET http://{{host}}/school HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 



# @name create_school
POST  http://{{host}}/school HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Escola modelo"
}

### 

# @name edsenso_city
GET http://{{host}}/edcensoCity HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name instuctor-teacher
GET http://{{host}}/instructor HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name Calendar
GET http://{{host}}/calendar HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name /edcensoProfessionalEduCourse
GET http://{{host}}/edcensoProfessionalEduCourse HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 