default_platform(:android)

platform :android do
  desc "Deploy a new version to alpha channel"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
      json_key_data: ENV['SUPPLY_JSON_KEY_DATA']
      package_name: ENV['SUPPLY_PACKAGE_NAME']
      track: 'alpha'
    )
  end
end
