// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6iyENmVrrcBls4I61pR2-JxNPF1p_VPc',
    appId: '1:60043627213:web:47ccc4a325df3d72973784',
    messagingSenderId: '60043627213',
    projectId: 'br-org-ipti-tag',
    authDomain: 'br-org-ipti-tag.firebaseapp.com',
    storageBucket: 'br-org-ipti-tag.appspot.com',
    measurementId: 'G-XKN8W6PZT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDayaaQoVi0STvZTpllNJk1NYNNRfzww-Y',
    appId: '1:60043627213:android:50acfb64097a9570973784',
    messagingSenderId: '60043627213',
    projectId: 'br-org-ipti-tag',
    storageBucket: 'br-org-ipti-tag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6xwddLBHWZpwrrXzUCnab-uguKEw3k70',
    appId: '1:60043627213:ios:f2874bddd48ef723973784',
    messagingSenderId: '60043627213',
    projectId: 'br-org-ipti-tag',
    storageBucket: 'br-org-ipti-tag.appspot.com',
    iosClientId: '60043627213-gbrsdt7mb1ll6r0incdhpggkp04iuinl.apps.googleusercontent.com',
    iosBundleId: 'br.org.ipti.tag',
  );
}
