import 'package:freezed_annotation/freezed_annotation.dart';

part 'classroom.freezed.dart';
part 'classroom.g.dart';

@freezed
class Classroom with _$Classroom {
  const factory Classroom({
    int? id,
    String? registerType,
    String? schoolIdentification,
    String? inepId,
    String? name,
    int? pedagogicalMediationType,
    String? initialHour,
    String? initialMinute,
    String? finalHour,
    String? finalMinute,
    bool? weekDaysSunday,
    bool? weekDaysMonday,
    bool? weekDaysTuesday,
    bool? weekDaysWednesday,
    bool? weekDaysThursday,
    bool? weekDaysFriday,
    bool? weekDaysSaturday,
    bool? complementaryActivity,
    bool? aee,
    int? assistanceType,
    int? maisEducacaoParticipator,
    int? complementaryActivityType1,
    int? complementaryActivityType2,
    int? complementaryActivityType3,
    int? complementaryActivityType4,
    int? complementaryActivityType5,
    int? complementaryActivityType6,
    bool? aeeBraille,
    bool? aeeOpticalNonoptical,
    bool? aeeCognitiveFunctions,
    bool? aeeMobilityTechniques,
    bool? aeeLibras,
    bool? aeeCaa,
    bool? aeeCurriculumEnrichment,
    bool? aeeSoroban,
    bool? aeeAccessibleTeaching,
    bool? aeePortuguese,
    bool? aeeAutonomousLife,
    int? modality,
    String? edcensoStageVsModalityFk,
    int? edcensoProfessionalEducationCourse,
    int? disciplineChemistry,
    int? disciplinePhysics,
    int? disciplineMathematics,
    int? disciplineBiology,
    int? disciplineScience,
    int? disciplineLanguagePortugueseLiterature,
    int? disciplineForeignLanguageEnglish,
    int? disciplineForeignLanguageSpanish,
    int? disciplineForeignLanguageFranch,
    int? disciplineForeignLanguageOther,
    int? disciplineArts,
    int? disciplinePhysicalEducation,
    int? disciplineHistory,
    int? disciplineGeography,
    int? disciplinePhilosophy,
    int? disciplineSocialStudy,
    int? disciplineSociology,
    int? disciplineProtugueseSecondaryLanguage,
    int? disciplineCurricularStage,
    int? disciplineInformatics,
    int? disciplineProfessionalDisciplines,
    int? disciplineSpecialEducationAndInclusivePractices,
    int? disciplineSocioculturalDiversity,
    int? disciplineLibras,
    int? disciplinePedagogical,
    int? disciplineReligious,
    int? disciplineNativeLanguage,
    int? disciplineOthers,
    int? schoolYear,
    String? turn,
    String? createDate,
    int? hash,
    int? calendar,
    bool? schooling,
    int? diffLocation,
    int? course,
  }) = _Classroom;

  factory Classroom.fromJson(Map<String, Object?> json) =>
      _$ClassroomFromJson(json);
}
