import 'dart:convert';

// Generated by https://quicktype.io

class Instructor {
  final String? neighborhood;
  final String? complement;
  final String? addressNumber;
  final String? address;
  final String? cep;
  final String? diffLocation;
  final int? areaOfResidence;
  final String? cpf;
  final bool otherCoursesNone;
  final bool otherCoursesOther;
  final bool otherCoursesEthnicEducation;
  final bool otherCoursesChildAndTeenageRights;
  final bool otherCoursesSexualEducation;
  final bool otherCoursesHumanRightsEducation;
  final bool otherCoursesEnvironmentEducation;
  final bool otherCoursesFieldEducation;
  final bool otherCoursesNativeEducation;
  final bool otherCoursesSpecialEducation;
  final bool otherCoursesEducationOfYouthAndAdults;
  final bool otherCoursesHighSchool;
  final bool otherCoursesBasicEducationFinalYears;
  final bool otherCoursesBasicEducationInitialYears;
  final bool otherCoursesPreSchool;
  final bool otherCoursesNursery;
  final bool postGraduationNone;
  final bool postGraduationDoctorate;
  final bool postGraduationMaster;
  final bool postGraduationSpecialization;
  final bool highEducationInstitutionCode3Fk;
  final bool highEducationFinalYear3;
  final bool highEducationInitialYear3;
  final bool highEducationCourseCode3Fk;
  final bool highEducationFormation3;
  final bool highEducationSituation3;
  final bool highEducationInstitutionCode2Fk;
  final bool highEducationFinalYear2;
  final bool highEducationInitialYear2;
  final bool highEducationCourseCode2Fk;
  final bool highEducationFormation2;
  final bool highEducationSituation2;
  final bool highEducationInstitutionCode1Fk;
  final bool highEducationFinalYear1;
  final bool highEducationInitialYear1;
  final bool highEducationCourseCode1Fk;
  final bool highEducationFormation1;
  final bool highEducationSituation1;
  final String? hash;
  final bool deficiencyTypeGifted;
  final bool deficiencyTypeAutism;
  final bool deficiencyTypeMultipleDisabilities;
  final bool deficiencyTypeIntelectualDisability;
  final bool deficiencyTypePhisicalDisability;
  final bool deficiencyTypeDeafblindness;
  final bool deficiencyTypeDisabilityHearing;
  final bool deficiencyTypeDeafness;
  final bool deficiencyTypeLowVision;
  final bool deficiencyTypeBlindness;
  final String? filiation2;
  final String? filiation1;
  final int? filiation;
  final String? nis;
  final String? email;
  final String? inepId;
  final String? registerType;
  final String? id;
  final String? schoolInepIdFk;
  final String? name;
  final String? birthdayDate;
  final int? sex;
  final int? colorRace;
  final int? nationality;
  final String? edcensoNationFk;
  final String? edcensoUfFk;
  final String? edcensoCityFk;
  final bool deficiency;
  final int? scholarity;
  final String? createdAt;
  final String? updatedAt;

  Instructor({
    this.neighborhood,
    this.complement,
    this.addressNumber,
    this.address,
    this.cep,
    this.diffLocation,
    this.areaOfResidence,
    this.cpf,
    this.otherCoursesNone = false,
    this.otherCoursesOther = false,
    this.otherCoursesEthnicEducation = false,
    this.otherCoursesChildAndTeenageRights = false,
    this.otherCoursesSexualEducation = false,
    this.otherCoursesHumanRightsEducation = false,
    this.otherCoursesEnvironmentEducation = false,
    this.otherCoursesFieldEducation = false,
    this.otherCoursesNativeEducation = false,
    this.otherCoursesSpecialEducation = false,
    this.otherCoursesEducationOfYouthAndAdults = false,
    this.otherCoursesHighSchool = false,
    this.otherCoursesBasicEducationFinalYears = false,
    this.otherCoursesBasicEducationInitialYears = false,
    this.otherCoursesPreSchool = false,
    this.otherCoursesNursery = false,
    this.postGraduationNone = false,
    this.postGraduationDoctorate = false,
    this.postGraduationMaster = false,
    this.postGraduationSpecialization = false,
    this.highEducationInstitutionCode3Fk = false,
    this.highEducationFinalYear3 = false,
    this.highEducationInitialYear3 = false,
    this.highEducationCourseCode3Fk = false,
    this.highEducationFormation3 = false,
    this.highEducationSituation3 = false,
    this.highEducationInstitutionCode2Fk = false,
    this.highEducationFinalYear2 = false,
    this.highEducationInitialYear2 = false,
    this.highEducationCourseCode2Fk = false,
    this.highEducationFormation2 = false,
    this.highEducationSituation2 = false,
    this.highEducationInstitutionCode1Fk = false,
    this.highEducationFinalYear1 = false,
    this.highEducationInitialYear1 = false,
    this.highEducationCourseCode1Fk = false,
    this.highEducationFormation1 = false,
    this.highEducationSituation1 = false,
    this.hash,
    this.deficiencyTypeGifted = false,
    this.deficiencyTypeAutism = false,
    this.deficiencyTypeMultipleDisabilities = false,
    this.deficiencyTypeIntelectualDisability = false,
    this.deficiencyTypePhisicalDisability = false,
    this.deficiencyTypeDeafblindness = false,
    this.deficiencyTypeDisabilityHearing = false,
    this.deficiencyTypeDeafness = false,
    this.deficiencyTypeLowVision = false,
    this.deficiencyTypeBlindness = false,
    this.filiation2,
    this.filiation1,
    this.filiation,
    this.nis,
    this.email,
    this.inepId,
    this.registerType,
    this.id,
    this.schoolInepIdFk,
    this.name,
    this.birthdayDate,
    this.sex,
    this.colorRace,
    this.nationality,
    this.edcensoNationFk,
    this.edcensoUfFk,
    this.edcensoCityFk,
    this.deficiency = false,
    this.scholarity,
    this.createdAt,
    this.updatedAt,
  });
}
